kind: pipeline
type: docker
name: amd64_build

platform:
  os: linux
  arch: amd64

steps:
- name: docker_build_version
  image: plugins/docker
  when:
    event:
      include:
        - push
    branch:
      include:
        - master
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: naorlivne/drone-github-changelog-generator
    tags:
      - linux-amd64
      - linux-amd64-v${DRONE_BUILD_NUMBER}

---
kind: pipeline
type: docker
name: arm64_build

platform:
  os: linux
  arch: arm64

steps:
- name: docker_build_version
  image: plugins/docker
  when:
    event:
      include:
        - push
    branch:
      include:
        - master
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: naorlivne/drone-github-changelog-generator
    tags:
      - linux-arm64
      - linux-arm64-v${DRONE_BUILD_NUMBER}

---
kind: pipeline
type: docker
name: arm_build

platform:
  os: linux
  arch: arm

steps:
- name: docker_build_version
  image: plugins/docker
  when:
    event:
      include:
        - push
    branch:
      include:
        - master
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: naorlivne/drone-github-changelog-generator
    tags:
      - linux-arm
      - linux-arm-v${DRONE_BUILD_NUMBER}

---
kind: pipeline
type: docker
name: publish_docker_manifest

trigger:
  branch:
    include:
      - master

steps:
- name: manifest
  image: plugins/manifest
  when:
    event:
      include:
        - push
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target:  naorlivne/drone-github-changelog-generator
    template: naorlivne/drone-github-changelog-generator:OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm

- name: create_changelog
  image: naorlivne/drone-github-changelog-generator
  settings:
    github_user: ${DRONE_REPO_NAMESPACE}
    github_project: ${DRONE_REPO_NAME}
  when:
    event:
      include:
        - push

- name: publish_github_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_api_key
    files: *
    title: v${DRONE_BUILD_NUMBER}
    note: CHANGELOG.md
  when:
    event:
      include:
        - push

depends_on:
- amd64_build
- arm64_build
- arm_build

---
kind: pipeline
type: docker
name: publish_docker_manifest_build_number

trigger:
  event:
  - push
  branch:
    include:
    - master

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target:  naorlivne/drone-github-changelog-generator:v${DRONE_BUILD_NUMBER}
    template: naorlivne/drone-github-changelog-generator:OS-ARCH-v${DRONE_BUILD_NUMBER}
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm

depends_on:
- amd64_build
- arm64_build
- arm_build

---
kind: pipeline
type: docker
name: notify

steps:
- name: notify
  image: drillster/drone-email
  settings:
    host: aspmx.l.google.com
    port: 25
    from: dronealert@dronealert.com
    recipients: [ naorlivne@gmail.com ]
    recipients_only: true

trigger:
  status:
  - failure

depends_on:
- publish_docker_manifest
- publish_docker_manifest_build_number
